### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [enico/ancientwisdom#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by enico** [comment]
Added <meta name="viewport" content="width=device-width, initial-scale=1.0"> to the application layout. It makes it look a tiny bit better than before.

**Comment by kenmazaika** [comment]
Thumbs up.  Great work on adding the viewport meta tag. :+1:
